services:
  # Serviço para o banco de dados MariaDB
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: oficina_web
      MYSQL_USER: user_app
      MYSQL_PASSWORD: password_app
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - oficina_network

  # Seu serviço da aplicação web (Flask)
  web:
    build: .
    image: igorkock/oficinaweb:latest
    container_name: oficinaweb
    ports:
      - "5000:5000"
    networks:
      - oficina_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: user_app
      DB_PASSWORD: password_app
      DB_HOST: db
      DB_NAME: oficina_web
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      TZ: America/Sao_Paulo # 🔹 NOVO: Define o fuso horário do contentor
      LANG: pt_BR.UTF-8    # 🔹 NOVO: Define o locale para pt-BR
    volumes:
      - .:/app
      - migrations_data:/app/migrations
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

volumes:
  db_data:
  migrations_data:

networks:
  oficina_network:
    driver: bridge