version: "3.8"

services:
  web:
    build: .
    container_name: oficinaweb
    ports:
      - "5000:5000"
    networks:
      - oficina_network
    command: python3 run.py

networks:
  oficina_network:
    driver: bridge
