"""Sincroniza esquema apos reset de historico de migrations

Revision ID: bf00ab0ba0bf
Revises: 
Create Date: 2025-07-06 11:24:55.891582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf00ab0ba0bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Limpa placas vazias antes de aplicar a restrição UNIQUE
    op.execute("UPDATE carros SET placa = CONCAT('TEMP-', id) WHERE placa = '';")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carros', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('quilometragem', sa.Integer(), nullable=True))
        #batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        #batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        #batch_op.alter_column('motor',
               #existing_type=mysql.VARCHAR(length=50),
               #nullable=True)
        batch_op.create_unique_constraint(None, ['placa'])
        batch_op.drop_column('quilometro')
        batch_op.drop_column('utilizador_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('apelido',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bairro',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)

    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('data',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('papeis', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('papeis', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('apelido',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')

    with op.batch_alter_table('carros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilizador_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quilometro', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('motor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('quilometragem')

    # ### end Alembic commands ###
